secretGenerator:
- name: mysql-pass
  literals:
  - username=docker
  - password=docker
  - rootpassword=docker
  - databasename=docker
  - datasource.url=jdbc:mysql://mysql:3306/
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml