apiVersion: v1
kind: Pod
metadata:
  labels:
    test: busybox
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600